name: 构建与打包

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: 设置 Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "npm"

      - name: 安装依赖
        run: npm ci

      - name: 编译插件
        run: npm run compile

      - name: 安装 vsce
        run: npm install -g @vscode/vsce

      - name: 打包插件
        run: vsce package -o designcj.vsix

      - name: 上传构建产物
        uses: actions/upload-artifact@v4
        with:
          name: designcj-extension
          path: designcj.vsix
          retention-days: 90
